---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service-blb-assignedid-eip
  annotations:
    service.beta.kubernetes.io/cce-load-balancer-exist-id: ""
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-blb-assignedid-eip
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80