---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service-blb-internal-vpc
  annotations:
    service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
spec:
  selector:
    app: nginx-blb-internal-vpc
  type: LoadBalancer
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-blb-internal-vpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-blb-internal-vpc
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
